_wandb:
    value:
        cli_version: 0.28.0
        e:
            sqz019fv3tngcge0ztw0j3pfbyzfdjxt:
                args:
                    - "0.30"
                    - "2.00"
                    - NO-FORD
                codePath: scripts/log_l2_run.py
                codePathLocal: scripts/log_l2_run.py
                email: jcerrell29@students.claremontmckenna.edu
                executable: /opt/homebrew/Caskroom/miniforge/base/envs/can-it-ford/bin/python
                host: Josies-MacBook-Air-2674.local
                os: macOS-15.0-arm64-arm-64bit
                program: /Users/josiecerrell/can-it-ford/scripts/log_l2_run.py
                python: CPython 3.12.13
                root: /Users/josiecerrell/can-it-ford
                startedAt: "2026-07-01T00:59:54.698202Z"
                writerId: sqz019fv3tngcge0ztw0j3pfbyzfdjxt
        m: []
        python_version: 3.12.13
        t:
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.12.13
            "5": 0.28.0
            "12": 0.28.0
            "13": darwin-arm64
compute:
    value: Vista_GH200
depth_m:
    value: 0.3
l1_threshold:
    value: 0.6
level:
    value: L2_Genesis_SPH
velocity_ms:
    value: 2
