_wandb:
    value:
        cli_version: 0.28.0
        e:
            ff9hf1uxhbivyx19lsuie9llpoo2z2ng:
                codePath: wandb_backfill.py
                codePathLocal: wandb_backfill.py
                email: jcerrell29@students.claremontmckenna.edu
                executable: /opt/homebrew/Caskroom/miniforge/base/envs/can-it-ford/bin/python
                host: Josies-MacBook-Air-2674.local
                os: macOS-15.0-arm64-arm-64bit
                program: /Users/josiecerrell/can-it-ford/wandb_backfill.py
                python: CPython 3.12.13
                root: /Users/josiecerrell/can-it-ford
                startedAt: "2026-07-01T06:12:05.578507Z"
                writerId: ff9hf1uxhbivyx19lsuie9llpoo2z2ng
        m: []
        python_version: 3.12.13
        t:
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.12.13
            "5": 0.28.0
            "10":
                - 20
            "12": 0.28.0
            "13": darwin-arm64
depth_m:
    value: 0.6
drift_threshold_m:
    value: 0.05
vehicle_class:
    value: 4WD
velocity_ms:
    value: 1.5
